### ISSUE TITLE
3.1.2: sphinx is failing

### ISSUE THREAD

**Issue by kloczek** [sphinx-toolbox/sphinx-toolbox#116]
```console
[tkloczko@devel-g2v sphinx-toolbox-3.1.2]$ /usr/bin/sphinx-build -n -T -b man doc-source build/sphinx/man
Running Sphinx v5.0.2

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/registry.py", line 430, in load_extension
    mod = import_module(extname)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-toolbox-3.1.2/./sphinx_toolbox/more_autodoc/autoprotocol.py", line 153, in <module>
    from sphinx_toolbox.more_autodoc.generic_bases import _add_generic_bases
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-toolbox-3.1.2/./sphinx_toolbox/more_autodoc/generic_bases.py", line 86, in <module>
    from sphinx_toolbox.more_autosummary import PatchedAutoSummClassDocumenter
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-toolbox-3.1.2/./sphinx_toolbox/more_autosummary/__init__.py", line 170, in <module>
    from sphinx.ext.autodoc.importer import get_module_members
ImportError: cannot import name 'get_module_members' from 'sphinx.ext.autodoc.importer' (/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 272, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 223, in __init__
    self.setup_extension(extension)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 380, in setup_extension
    self.registry.load_extension(self, extname)
  File "/usr/lib/python3.8/site-packages/sphinx/registry.py", line 443, in load_extension
    metadata = setup(app)
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-toolbox-3.1.2/./sphinx_toolbox/__init__.py", line 95, in setup
    app.setup_extension("sphinx_toolbox.more_autodoc.autoprotocol")
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 380, in setup_extension
    self.registry.load_extension(self, extname)
  File "/usr/lib/python3.8/site-packages/sphinx/registry.py", line 433, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname,
sphinx.errors.ExtensionError: Could not import extension sphinx_toolbox.more_autodoc.autoprotocol (exception: cannot import name 'get_module_members' from 'sphinx.ext.autodoc.importer' (/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py))

Extension error:
Could not import extension sphinx_toolbox.more_autodoc.autoprotocol (exception: cannot import name 'get_module_members' from 'sphinx.ext.autodoc.importer' (/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py))
```
And indeed it there is no that name 
```console
[tkloczko@devel-g2v sphinx-toolbox-3.1.2]$ grep get_module_members sphinx_toolbox/more_autodoc/autoprotocol.py
[tkloczko@devel-g2v sphinx-toolbox-3.1.2]$
```

**Comment by kloczek** [comment]
Just started testing 3.2.0 and looks like pytest is happy now.
<details>

```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-sphinx-toolbox-3.2.0-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-sphinx-toolbox-3.2.0-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra --ignore tests/test_tweaks/test_tabsize.py
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.13, pytest-7.1.2, pluggy-1.0.0
Test session started at 09:06:39
rootdir: /home/tkloczko/rpmbuild/BUILD/sphinx-toolbox-3.2.0, configfile: tox.ini
plugins: datadir-1.3.1, regressions-2.3.1, timeout-2.1.0, hypothesis-6.41.0, httpserver-1.0.4
timeout: 600.0s
timeout method: signal
timeout func_only: False
collected 2520 items

tests/test_assets.py .                                                                                                                                               [  0%]
tests/test_autosummary_widths.py .                                                                                                                                   [  0%]
tests/test_code.py ..                                                                                                                                                [  0%]
tests/test_config.py ......                                                                                                                                          [  0%]
tests/test_css.py ..                                                                                                                                                 [  0%]
tests/test_github.py ............................................................................................................................................... [  6%]
.................................................................................................................................................................... [ 12%]
.................................................................................................................................................................... [ 19%]
.................................................................................................................................................................... [ 25%]
.................................................................................................................................................................... [ 32%]
.................................................................................................................................................................... [ 38%]
.................................................................................................................................................................... [ 45%]
.........................................                                                                                                                            [ 46%]
tests/test_installation.py ...                                                                                                                                       [ 46%]
tests/test_issues.py ............................................................................................................................................... [ 52%]
.................................................................................................................................................................... [ 59%]
.................................................................................................................................................................... [ 65%]
.................................................................................................................................................................... [ 72%]
.................................................................................................................................................................... [ 78%]
.................................................................................................................................................................... [ 85%]
............................................................................................................................................                         [ 90%]
tests/test_latex.py ....                                                                                                                                             [ 90%]
tests/test_main.py .                                                                                                                                                 [ 90%]
tests/test_more_autosummary.py .                                                                                                                                     [ 90%]
tests/test_rest_example.py ..                                                                                                                                        [ 91%]
tests/test_setup.py .                                                                                                                                                [ 91%]
tests/test_shields.py ..                                                                                                                                             [ 91%]
tests/test_sidebar_links.py ....                                                                                                                                     [ 91%]
tests/test_source.py ....                                                                                                                                            [ 91%]
tests/test_testing.py .                                                                                                                                              [ 91%]
tests/test_utils.py .........................                                                                                                                        [ 92%]
tests/test_wikipedia.py ....                                                                                                                                         [ 92%]
tests/test_issues_output/test_source_output.py ...                                                                                                                   [ 92%]
tests/test_more_autodoc/test_augment_defaults.py ..                                                                                                                  [ 92%]
tests/test_more_autodoc/test_autodoc_typehints.py ...................ss......................................                                                        [ 95%]
tests/test_more_autodoc/test_autonamedtuple.py .                                                                                                                     [ 95%]
tests/test_more_autodoc/test_autoprotocol.py .                                                                                                                       [ 95%]
tests/test_more_autodoc/test_autotypeddict.py .                                                                                                                      [ 95%]
tests/test_more_autodoc/test_generic_bases.py .                                                                                                                      [ 95%]
tests/test_more_autodoc/test_genericalias.py .                                                                                                                       [ 95%]
tests/test_more_autodoc/test_no_docstring.py .                                                                                                                       [ 95%]
tests/test_more_autodoc/test_overloads.py .                                                                                                                          [ 95%]
tests/test_more_autodoc/test_regex.py ........................................................                                                                       [ 97%]
tests/test_more_autodoc/test_setup.py .                                                                                                                              [ 97%]
tests/test_more_autodoc/test_source_link.py .                                                                                                                        [ 97%]
tests/test_more_autodoc/test_sourcelink.py .                                                                                                                         [ 97%]
tests/test_more_autodoc/test_typehints.py ............s.s.s................s..                                                                                       [ 99%]
tests/test_more_autodoc/test_typevars.py .                                                                                                                           [ 99%]
tests/test_more_autodoc/test_variables.py ..                                                                                                                         [ 99%]
tests/test_output/test_output.py ........                                                                                                                            [ 99%]
tests/test_source_output_github/test_source_output.py ..                                                                                                             [ 99%]
tests/test_source_output_sphinx/test_source_output.py ..                                                                                                             [ 99%]
tests/test_tweaks/test_footnote_symbols.py .                                                                                                                         [ 99%]
tests/test_tweaks/test_param_dash.py .                                                                                                                               [ 99%]
tests/test_tweaks/test_sphinx_panels_tabs.py ..                                                                                                                      [100%]

=========================================================================== slowest 25 durations ===========================================================================
5.05s call     tests/test_output/test_output.py::test_html_output
4.17s call     tests/test_output/test_output.py::test_build_example
4.07s setup    tests/test_output/test_output.py::test_example_html_output[example.html]
4.05s setup    tests/test_issues_output/test_source_output.py::test_output_github[index.html]
3.80s call     tests/test_output/test_output.py::test_sidebar_links_output
3.14s call     tests/test_issues_output/test_source_output.py::test_build_github
3.01s call     tests/test_issues_output/test_source_output.py::test_html_output
1.85s call     tests/test_output/test_output.py::test_latex_output_better_header_layout
1.76s call     tests/test_output/test_output.py::test_latex_output
1.73s call     tests/test_output/test_output.py::test_latex_output_autosummary_col_type
1.73s call     tests/test_output/test_output.py::test_latex_output_latex_layout
0.50s call     tests/test_utils.py::test_escape_trailing_underscore
0.41s call     tests/test_autosummary_widths.py::test_latex_output
0.37s setup    tests/test_more_autodoc/test_autodoc_typehints.py::test_format_annotation[str-:py:class:`str`]
0.32s setup    tests/test_output/test_output.py::test_build_example
0.31s setup    tests/test_output/test_output.py::test_sidebar_links_output
0.29s setup    tests/test_output/test_output.py::test_html_output
0.29s setup    tests/test_output/test_output.py::test_latex_output_latex_layout
0.29s setup    tests/test_output/test_output.py::test_latex_output
0.28s setup    tests/test_output/test_output.py::test_latex_output_autosummary_col_type
0.28s setup    tests/test_output/test_output.py::test_latex_output_better_header_layout
0.28s call     tests/test_github.py::test_visit_issue_node
0.22s teardown tests/test_tweaks/test_sphinx_panels_tabs.py::test_setup
0.20s setup    tests/test_source_output_sphinx/test_source_output.py::test_output_sphinx[index.html]
0.20s call     tests/test_github.py::test_visit_issue_node_errors[HTTPStatus.UPGRADE_REQUIRED]
========================================================================= short test summary info ==========================================================================
SKIPPED [2] tests/test_more_autodoc/test_autodoc_typehints.py:104: Introduced in 3.10
SKIPPED [3] tests/test_more_autodoc/test_typehints.py:36: PyPy reuses some types
SKIPPED [1] tests/test_more_autodoc/test_typehints.py:36: Introduced in 3.10
===================================================================== 2514 passed, 6 skipped in 52.13s =====================================================================
```
<details>

Closing.
