### ISSUE TITLE
sphinx-build fails to load the `sphinx_toolbox.more_autodoc` because of a missing `github_username`

### ISSUE THREAD

**Issue by daureg** [sphinx-toolbox/sphinx-toolbox#134]
## Description

sphinx-build fails to load the `sphinx_toolbox.more_autodoc` because of a missing `github_username` in the configuration. I supposed in my CI system I could set a fake username, but that still seems unnecessary

## Steps to Reproduce

   1. `pip install sphinx-toolbox==3.2.0`
   2. write a simple conf.py
```project = 'bug'
extensions = ["sphinx_toolbox.more_autodoc"]
```
   3. `sphinx-build . _build`

## Actual result:

```python
[app] emitting event: 'config-inited'(<sphinx.config.Config object at 0x7fcb515a9820>,)

Traceback (most recent call last):
  File "/home/glefalher/.pyenv/versions/3.9.13/lib/python3.9/site-packages/sphinx/events.py", line 94, in emit
    results.append(listener.handler(self.app, *args))
  File "/home/glefalher/.pyenv/versions/3.9.13/lib/python3.9/site-packages/sphinx_toolbox/github/__init__.py", line 246, in validate_config
    raise MissingOptionError("The 'github_username' option is required.")
sphinx_toolbox.config.MissingOptionError: The 'github_username' option is required.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/glefalher/.pyenv/versions/3.9.13/lib/python3.9/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/home/glefalher/.pyenv/versions/3.9.13/lib/python3.9/site-packages/sphinx/application.py", line 247, in __init__
    self.events.emit('config-inited', self.config)
  File "/home/glefalher/.pyenv/versions/3.9.13/lib/python3.9/site-packages/sphinx/events.py", line 105, in emit
    raise ExtensionError(__("Handler %r for event %r threw an exception") %
sphinx.errors.ExtensionError: Handler <function validate_config at 0x7fcb504cf4c0> for event 'config-inited' threw an exception (exception: The 'github_username' option is required.)

Extension error (sphinx_toolbox.github):
Handler <function validate_config at 0x7fcb504cf4c0> for event 'config-inited' threw an exception (exception: The 'github_username' option is required.)
```

## Expected result:

sphinx-build start building the documentation

## Reproduces how often:

Easily reproduced

## Version

  * Operating System: linux
  * Python: 3.9.13
  * sphinx-toolbox: 3.2.0

## Installation source

pip

**Comment by Rage997** [comment]
Wondering if there's any update on this issue? It seems a bit weird that you have to specify a GitHub configuration, necessary.
