### ISSUE TITLE
Sphinx 8 compatibility

### ISSUE THREAD

**Issue by flying-sheep** [sphinx-toolbox/sphinx-toolbox#168]
## Description
In Sphinx 7, you already saw

```
 …/site-packages/sphinx_toolbox/more_autodoc/autoprotocol.py:324:
  RemovedInSphinx80Warning:
  The tuple interface of ObjectMember is deprecated. Use (obj.__name__, obj.object) instead. 
```

## Steps to Reproduce
Use e.g. autoprotocol with sphinx 8

## Actual result:
```pytb
Traceback (most recent call last):
  File "/home/phil/.local/share/hatch/env/virtual/anndata/PUvSwSLS/docs/lib/python3.12/site-packages/sphinx/cmd/build.py", line 337, in build_main
    app.build(args.force_all, args.filenames)
  File "/home/phil/.local/share/hatch/env/virtual/anndata/PUvSwSLS/docs/lib/python3.12/site-packages/sphinx/application.py", line 378, in build
    self.builder.build_update()
  File "/home/phil/.local/share/hatch/env/virtual/anndata/PUvSwSLS/docs/lib/python3.12/site-packages/sphinx/builders/__init__.py", line 296, in build_update
    self.build(to_build,
  File "/home/phil/.local/share/hatch/env/virtual/anndata/PUvSwSLS/docs/lib/python3.12/site-packages/sphinx/builders/__init__.py", line 317, in build
    updated_docnames = set(self.read())
                           ^^^^^^^^^^^
  File "/home/phil/.local/share/hatch/env/virtual/anndata/PUvSwSLS/docs/lib/python3.12/site-packages/sphinx/builders/__init__.py", line 424, in read
    self._read_serial(docnames)
  File "/home/phil/.local/share/hatch/env/virtual/anndata/PUvSwSLS/docs/lib/python3.12/site-packages/sphinx/builders/__init__.py", line 476, in _read_serial
    self.read_doc(docname)
  File "/home/phil/.local/share/hatch/env/virtual/anndata/PUvSwSLS/docs/lib/python3.12/site-packages/sphinx/builders/__init__.py", line 535, in read_doc
    publisher.publish()
  File "/home/phil/.local/share/hatch/env/virtual/anndata/PUvSwSLS/docs/lib/python3.12/site-packages/docutils/core.py", line 234, in publish
    self.document = self.reader.read(self.source, self.parser,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/phil/.local/share/hatch/env/virtual/anndata/PUvSwSLS/docs/lib/python3.12/site-packages/sphinx/io.py", line 106, in read
    self.parse()
  File "/home/phil/.local/share/hatch/env/virtual/anndata/PUvSwSLS/docs/lib/python3.12/site-packages/docutils/readers/__init__.py", line 76, in parse
    self.parser.parse(self.input, document)
  File "/home/phil/.local/share/hatch/env/virtual/anndata/PUvSwSLS/docs/lib/python3.12/site-packages/sphinx/parsers.py", line 83, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/home/phil/.local/share/hatch/env/virtual/anndata/PUvSwSLS/docs/lib/python3.12/site-packages/docutils/parsers/rst/states.py", line 169, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/phil/.local/share/hatch/env/virtual/anndata/PUvSwSLS/docs/lib/python3.12/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
                                  ^^^^^^^^^^^^^^^^
  File "/home/phil/.local/share/hatch/env/virtual/anndata/PUvSwSLS/docs/lib/python3.12/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/phil/.local/share/hatch/env/virtual/anndata/PUvSwSLS/docs/lib/python3.12/site-packages/docutils/parsers/rst/states.py", line 2790, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/phil/.local/share/hatch/env/virtual/anndata/PUvSwSLS/docs/lib/python3.12/site-packages/docutils/parsers/rst/states.py", line 325, in section
    self.new_subsection(title, lineno, messages)
  File "/home/phil/.local/share/hatch/env/virtual/anndata/PUvSwSLS/docs/lib/python3.12/site-packages/docutils/parsers/rst/states.py", line 391, in new_subsection
    newabsoffset = self.nested_parse(
                   ^^^^^^^^^^^^^^^^^^
  File "/home/phil/.local/share/hatch/env/virtual/anndata/PUvSwSLS/docs/lib/python3.12/site-packages/docutils/parsers/rst/states.py", line 279, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/home/phil/.local/share/hatch/env/virtual/anndata/PUvSwSLS/docs/lib/python3.12/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/phil/.local/share/hatch/env/virtual/anndata/PUvSwSLS/docs/lib/python3.12/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
                                  ^^^^^^^^^^^^^^^^
  File "/home/phil/.local/share/hatch/env/virtual/anndata/PUvSwSLS/docs/lib/python3.12/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/phil/.local/share/hatch/env/virtual/anndata/PUvSwSLS/docs/lib/python3.12/site-packages/docutils/parsers/rst/states.py", line 2359, in explicit_markup
    self.explicit_list(blank_finish)
  File "/home/phil/.local/share/hatch/env/virtual/anndata/PUvSwSLS/docs/lib/python3.12/site-packages/docutils/parsers/rst/states.py", line 2384, in explicit_list
    newline_offset, blank_finish = self.nested_list_parse(
                                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/phil/.local/share/hatch/env/virtual/anndata/PUvSwSLS/docs/lib/python3.12/site-packages/docutils/parsers/rst/states.py", line 316, in nested_list_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/home/phil/.local/share/hatch/env/virtual/anndata/PUvSwSLS/docs/lib/python3.12/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/phil/.local/share/hatch/env/virtual/anndata/PUvSwSLS/docs/lib/python3.12/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
                                  ^^^^^^^^^^^^^^^^
  File "/home/phil/.local/share/hatch/env/virtual/anndata/PUvSwSLS/docs/lib/python3.12/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/phil/.local/share/hatch/env/virtual/anndata/PUvSwSLS/docs/lib/python3.12/site-packages/docutils/parsers/rst/states.py", line 2662, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/phil/.local/share/hatch/env/virtual/anndata/PUvSwSLS/docs/lib/python3.12/site-packages/docutils/parsers/rst/states.py", line 2369, in explicit_construct
    return method(self, expmatch)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/phil/.local/share/hatch/env/virtual/anndata/PUvSwSLS/docs/lib/python3.12/site-packages/docutils/parsers/rst/states.py", line 2106, in directive
    return self.run_directive(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/phil/.local/share/hatch/env/virtual/anndata/PUvSwSLS/docs/lib/python3.12/site-packages/docutils/parsers/rst/states.py", line 2156, in run_directive
    result = directive_instance.run()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/phil/.local/share/hatch/env/virtual/anndata/PUvSwSLS/docs/lib/python3.12/site-packages/sphinx/ext/autodoc/directive.py", line 139, in run
    documenter.generate(more_content=self.content)
  File "/home/phil/.local/share/hatch/env/virtual/anndata/PUvSwSLS/docs/lib/python3.12/site-packages/sphinx/ext/autodoc/__init__.py", line 1872, in generate
    return super().generate(more_content=more_content,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/phil/.local/share/hatch/env/virtual/anndata/PUvSwSLS/docs/lib/python3.12/site-packages/sphinx/ext/autodoc/__init__.py", line 943, in generate
    self.document_members(all_members)
  File "/home/phil/.local/share/hatch/env/virtual/anndata/PUvSwSLS/docs/lib/python3.12/site-packages/sphinx_toolbox/more_autodoc/autoprotocol.py", line 307, in document_members
    super().document_members(True)
  File "/home/phil/.local/share/hatch/env/virtual/anndata/PUvSwSLS/docs/lib/python3.12/site-packages/sphinx/ext/autodoc/__init__.py", line 1858, in document_members
    super().document_members(all_members)
  File "/home/phil/.local/share/hatch/env/virtual/anndata/PUvSwSLS/docs/lib/python3.12/site-packages/sphinx/ext/autodoc/__init__.py", line 799, in document_members
    for (mname, member, isattr) in self.filter_members(members, want_all):
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/phil/.local/share/hatch/env/virtual/anndata/PUvSwSLS/docs/lib/python3.12/site-packages/sphinx_toolbox/more_autodoc/autoprotocol.py", line 324, in filter_members
    for (membername, member) in members:
        ^^^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable ObjectMember object
```

## Expected result:
you run your tests so they fail when encountering a deprecationwarning and fix things before deprecations become removals

## Reproduces how often:
yes

## Version

  * Operating System: irrelevant
  * Python: irrelevant
  * sphinx-toolbox: 3.7.0

## Installation source
pip

**Comment by flying-sheep** [comment]
Fixed in 18333be923acb4b988efc03db94070349d598a97
